---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
  - image: ansible-centos:8
  - image: ansible-centos:7
  - image: ansible-fedora:29
  - image: ansible-fedora:28
  - image: ansible-fedora:27
  - image: ansible-fedora:26
  - image: ansible-ubuntu:18.04
  - image: ansible-ubuntu:16.04
  - image: ansible-ubuntu:14.04
  - image: ansible-debian:10
  - image: ansible-debian:9
  - image: ansible-debian:8
  - image: ansible-oraclelinux:7
  - image: ansible-amazonlinux:2
  - image: ansible-amazonlinux:1

before_install:
  - 'docker pull diodonfrost/${image}'

install:
  - pip install -r requirements.txt

script:
  - image=${image} molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
