---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
  - distribution: centos-8
  - distribution: centos-7
  - distribution: fedora-29
  - distribution: fedora-28
  - distribution: fedora-27
  - distribution: fedora-26
  - distribution: ubuntu-18.04
  - distribution: ubuntu-16.04
  - distribution: ubuntu-14.04
  - distribution: debian-10
  - distribution: debian-9
  - distribution: debian-8
  - distribution: oraclelinux-7
  - distribution: amazonlinux-2
  - distribution: amazonlinux-1

before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - pip install ansible==2.9.4 molecule==3.0.2 docker==4.2.2

script:
  - distribution=${distribution} molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
