---

- name: Linux | Install package requirements
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_requirements }}"

- name: Linux | Download CodeDeploy
  get_url:
    url: "{{ codedeploy_install_script_url }}"
    dest: /tmp/codedeploy-install
    mode: '0750'
  register: command_result

- name: Linux | Install CodeDeploy
  command: /tmp/codedeploy-install auto
  when: command_result.changed

- name: Linux | CodeDeploy service
  service:
    name: codedeploy-agent
    state: started
    enabled: yes
